export const NEW_INPUT = 'NEW_INPUT';

export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST';
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCHED_REPOS = 'FETCHED_REPOS';
export const FETCHED_COMMITS = 'FETCHED_COMMITS';